service:
  name: developer-service

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters
  - serverless-webpack
  - serverless-s3-sync

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 256
  stage: ${opt:stage, 'dev'}
  region: us-east-2
  environment:
    USERS_TABLE_NAME: ${self:custom.UsersTable.name}
  iamRoleStatements:
    - ${file(iam/UsersTableIAM.yml):UsersTableIAM}

resources:
  Resources:
    DevelopersBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
        AccessControl: PublicRead
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
    S3AccessPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
          Bucket:
              Ref: DevelopersBucket
          PolicyDocument:
              Statement:
                  - Sid: PublicReadGetObject
                    Effect: Allow
                    Principal: '*'
                    Action:
                        - s3:GetObject
                    Resource: arn:aws:s3:::${self:custom.bucketName}/*
    UsersTable: ${file(resources/UsersTable.yml):UsersTable}
    CloudFrontDistribution:
            Type: AWS::CloudFront::Distribution
            Properties:
                DistributionConfig:
                    Origins:
                        - DomainName: ${self:custom.bucketName}.s3.amazonaws.com
                          Id: ReactApp
                          CustomOriginConfig:
                              HTTPPort: 80
                              HTTPSPort: 443
                              OriginProtocolPolicy: https-only
                    Enabled: 'true'
                    DefaultRootObject: index.html
                    CustomErrorResponses:
                        - ErrorCode: 404
                          ResponseCode: 200
                          ResponsePagePath: /index.html
                    DefaultCacheBehavior:
                        AllowedMethods:
                            - DELETE
                            - GET
                            - HEAD
                            - OPTIONS
                            - PATCH
                            - POST
                            - PUT
                        TargetOriginId: ReactApp
                        ForwardedValues:
                            QueryString: 'false'
                            Cookies:
                                Forward: none
                        ViewerProtocolPolicy: redirect-to-https
                    ViewerCertificate:
                        CloudFrontDefaultCertificate: true

functions:
  createUser:
    handler: src/handlers/createUser.handler
    events:
      - http:
          method: POST
          path: /user

          cors: true

  getUsers:
    handler: src/handlers/getUsers.handler
    events:
      - http:
          method: GET
          path: /users
          cors: true

custom:
  bucketName: developer-service-social-06-19
  s3Sync:
    - bucketName: ${self:custom.bucketName}
      localDir: frontend/build/
  UsersTable:
    name: !Ref UsersTable
    arn:  !GetAtt UsersTable.Arn
  bundle:
    linting: true

      